[project]
name = "python-app2"
version = "0.1.0"
description = "A simple python app (no --package)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
    "python-lib"
]

[project.scripts]
python-app = "python_app:main"

